# Generated by Django 3.0.4 on 2020-03-28 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputtext',
            name='summary',
            field=models.CharField(default='', max_length=25000),
        ),
    ]
