# Generated by Django 3.0.4 on 2020-03-28 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_inputtext_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebScrape',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=1000)),
                ('story', models.CharField(max_length=25000)),
            ],
        ),
    ]
