# Generated by Django 3.0.4 on 2020-03-28 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_webscrape'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputtext',
            name='rouge',
            field=models.CharField(default='', max_length=500),
        ),
    ]
