# Generated by Django 3.0.4 on 2020-03-28 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_inputtext_rouge'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputtext',
            name='pub_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
